language: java
cache:
  directories:
  - $HOME/.m2
branches:
 only:
   - master
dist: trusty
services:
  - mysql
addons:
  apt:
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - oracle-java8-set-default
before_install:
  - mysql -u root < src/main/resources/db/creation.sql
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 5
  - chmod +x src/main/resources/selenium/linux/chromedriver
  - mvn test